### ISSUE TITLE
🐛 Bug:  Cloning Issue

### ISSUE THREAD

**Issue by Sahillather002** [uclaacm/recursion-lab#235]
### Is there an existing issue for this?

- [x] I have searched existing issues

### What happened?

Every time i try to clone it throughs me this error.
Can anyone help me with this.

![image](https://github.com/uclaacm/recursion-lab/assets/72077931/0feedcb9-7db6-4c68-bf24-2eea1e56c9ca)

**Comment by EDWIN1669086** [comment]
@Sahillather002 It appears the problem was an empty file named `Icon`, presumably due to the lack of file extension and the Windows operating system with particular characters, referenced [here](https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl). Let me know if the issue persists.
